"""Daily "veille" recap email, rendered per recipient in their language.

The daily agent inserts articles through ``POST /articles/ingest`` and then calls
``POST /notify/veille`` with the article ids. This module builds one HTML email per
recipient (FR / EN / AR, RTL for Arabic) with a link to each article on the platform
and to its original source, and sends it through Resend.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date
from html import escape

from sqlalchemy.orm import Session, joinedload

from workers.src.config import settings
from workers.src.models.article import (
    Article,
    NotificationLog,
    User,
    UserNotificationStatus,
    UserPreferences,
)
from workers.src.notifiers.email import send_email

logger = logging.getLogger(__name__)

SUPPORTED_LANGUAGES = ("fr", "en", "ar")

LABELS: dict[str, dict[str, str]] = {
    "fr": {
        "brand": "Veille AI",
        "subject": "Veille AI — {date} — {n} articles ({inserted} insérés, {skipped} doublons)",
        "counters": "{n} articles · {inserted} insérés · {skipped} doublons",
        "day_link": "Voir les articles du jour sur AI News →",
        "view": "Voir sur AI News →",
        "source": "Lire la source →",
        "footer": "Généré par Claude · Base : {base}",
        "empty": "Aucun article aujourd'hui.",
    },
    "en": {
        "brand": "AI News Digest",
        "subject": "AI News Digest — {date} — {n} articles ({inserted} new, {skipped} duplicates)",
        "counters": "{n} articles · {inserted} new · {skipped} duplicates",
        "day_link": "See today's articles on AI News →",
        "view": "View on AI News →",
        "source": "Read the source →",
        "footer": "Generated by Claude · Platform: {base}",
        "empty": "No articles today.",
    },
    "ar": {
        "brand": "نشرة أخبار الذكاء الاصطناعي",
        "subject": "نشرة الذكاء الاصطناعي — {date} — {n} مقالات ({inserted} جديدة، {skipped} مكررة)",
        "counters": "{n} مقالات · {inserted} جديدة · {skipped} مكررة",
        "day_link": "← عرض مقالات اليوم على AI News",
        "view": "← عرض على AI News",
        "source": "← قراءة المصدر",
        "footer": "أُنشئت بواسطة Claude · المنصة: {base}",
        "empty": "لا توجد مقالات اليوم.",
    },
}


@dataclass(frozen=True)
class Recipient:
    """One email recipient and the language to render for them."""

    email: str
    language: str = "fr"
    user_id: str | None = None


def normalize_language(value: str | None) -> str:
    """Map any stored language value to a supported code (defaults to French)."""
    lang = (value or "fr").lower()[:2]
    return lang if lang in SUPPORTED_LANGUAGES else "fr"


def localized_fields(article: Article, language: str) -> tuple[str, str]:
    """Return (title, summary) in the requested language with sensible fallbacks."""
    if language == "en":
        title = article.title_en or article.title_fr or article.original_title
        summary = article.summary_en or article.summary_fr or ""
    elif language == "ar":
        title = article.title_ar or article.title_fr or article.original_title
        summary = article.summary_ar or article.summary_fr or ""
    else:
        title = article.title_fr or article.original_title
        summary = article.summary_fr or ""
    return title or "", summary or ""


def format_date(day: date, language: str) -> str:
    """Date as shown in the subject and header (DD/MM/YYYY for FR and AR, ISO for EN)."""
    return day.isoformat() if language == "en" else day.strftime("%d/%m/%Y")


def _score_badge(score: float) -> str:
    color = "#16a34a" if score >= 9 else ("#2563eb" if score >= 7 else "#6b7280")
    return (
        f'<span style="display:inline-block;background:{color};color:#fff;font-weight:700;'
        f'font-size:12px;padding:2px 8px;border-radius:12px">{score:g}/10</span>'
    )


def build_veille_email(
    articles: list[Article],
    language: str,
    day: date,
    inserted_count: int,
    skipped_count: int,
    web_base_url: str | None = None,
) -> tuple[str, str]:
    """Build the (subject, html) pair for one language.

    Articles are sorted by score (descending); each card links to the article page on
    the platform (``/<lang>/articles/<id>``) and to the original source.
    """
    language = normalize_language(language)
    labels = LABELS[language]
    base = (web_base_url or settings.web_base_url).rstrip("/")
    ordered = sorted(articles, key=lambda a: -(a.score or 0))
    date_label = format_date(day, language)
    n = len(ordered)

    subject = labels["subject"].format(
        date=date_label, n=n, inserted=inserted_count, skipped=skipped_count
    )
    counters = labels["counters"].format(n=n, inserted=inserted_count, skipped=skipped_count)
    day_url = f"{base}/{language}/articles?from={day.isoformat()}&to={day.isoformat()}&tz=180"
    direction = "rtl" if language == "ar" else "ltr"
    align = "right" if language == "ar" else "left"

    cards: list[str] = []
    for a in ordered:
        title, summary = localized_fields(a, language)
        platform_url = f"{base}/{language}/articles/{a.id}"
        source_name = a.source.name if getattr(a, "source", None) else ""
        published = a.published_at.strftime("%d/%m/%Y") if a.published_at else ""
        meta = " · ".join(x for x in (escape(source_name), published) if x)
        cards.append(
            f'<div style="border:1px solid #e5e7eb;border-radius:10px;padding:16px;margin:0 0 14px 0;background:#ffffff">'
            f'<div style="font-size:12px;color:#6b7280;margin-bottom:6px">{meta} · {_score_badge(a.score or 0)}</div>'
            f'<div style="font-size:17px;font-weight:700;line-height:1.3;margin-bottom:8px">'
            f'<a href="{platform_url}" style="color:#111827;text-decoration:none">{escape(title)}</a></div>'
            f'<div style="font-size:14px;line-height:1.5;color:#374151;margin-bottom:12px">{escape(summary)}</div>'
            f'<a href="{platform_url}" style="display:inline-block;font-size:13px;font-weight:600;color:#ffffff;'
            f'background:#2563eb;padding:6px 12px;border-radius:8px;text-decoration:none;margin-inline-end:10px">'
            f'{labels["view"]}</a>'
            f'<a href="{escape(a.url)}" style="font-size:13px;color:#2563eb;text-decoration:none">{labels["source"]}</a>'
            f"</div>"
        )

    body = "".join(cards) if cards else (
        f'<p style="color:#6b7280;font-size:14px">{labels["empty"]}</p>'
    )
    footer = labels["footer"].format(base=f'<a href="{base}" style="color:#6b7280">{base}</a>')

    html = (
        f'<div dir="{direction}" style="max-width:680px;margin:0 auto;text-align:{align};'
        f'font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:#f9fafb;padding:16px">'
        f'<div style="background:#111827;color:#ffffff;border-radius:10px;padding:18px 20px;margin-bottom:16px">'
        f'<div style="font-size:20px;font-weight:700">{labels["brand"]} — {date_label}</div>'
        f'<div style="font-size:13px;color:#d1d5db;margin-top:4px">{counters}</div>'
        f'<div style="font-size:13px;margin-top:8px"><a href="{escape(day_url)}" style="color:#93c5fd;text-decoration:none">'
        f'{labels["day_link"]}</a></div></div>'
        f"{body}"
        f'<div style="font-size:12px;color:#6b7280;text-align:center;margin-top:8px">{footer}</div>'
        f"</div>"
    )
    return subject, html


def platform_recipients(db: Session) -> list[Recipient]:
    """Users who opted into email notifications, each with their preferred language.

    Users whose subscription exists but is neither active nor trialing are skipped,
    matching the digest logic.
    """
    users = (
        db.query(User)
        .join(UserPreferences)
        .options(joinedload(User.preferences), joinedload(User.subscription))
        .filter(UserPreferences.email_notifications == True)  # noqa: E712
        .all()
    )
    recipients: list[Recipient] = []
    for user in users:
        if not user.email or not user.preferences:
            continue
        if user.subscription and user.subscription.status not in ("active", "trialing"):
            continue
        recipients.append(
            Recipient(
                email=user.email,
                language=normalize_language(user.preferences.language),
                user_id=user.id,
            )
        )
    return recipients


def merge_recipients(primary: list[Recipient], extra: list[Recipient]) -> list[Recipient]:
    """Append extra recipients whose email is not already covered (case-insensitive)."""
    seen = {r.email.lower() for r in primary}
    merged = list(primary)
    for r in extra:
        key = r.email.lower()
        if key in seen:
            continue
        seen.add(key)
        merged.append(Recipient(email=r.email, language=normalize_language(r.language), user_id=r.user_id))
    return merged


async def send_veille(
    db: Session,
    articles: list[Article],
    recipients: list[Recipient],
    day: date,
    inserted_count: int,
    skipped_count: int,
    dry_run: bool = False,
) -> dict:
    """Send the recap to every recipient in their language; returns a summary dict."""
    by_language: dict[str, int] = {}
    sent: list[str] = []
    failed: list[str] = []
    rendered: dict[str, tuple[str, str]] = {}

    for r in recipients:
        by_language[r.language] = by_language.get(r.language, 0) + 1
        if dry_run:
            continue
        if r.language not in rendered:
            rendered[r.language] = build_veille_email(
                articles, r.language, day, inserted_count, skipped_count
            )
        subject, html = rendered[r.language]
        ok = await send_email(r.email, subject, html)
        (sent if ok else failed).append(r.email)
        db.add(
            NotificationLog(
                type="email_veille",
                recipient=r.email,
                content=subject,
                success=ok,
                user_id=r.user_id,
            )
        )
        if ok and r.user_id:
            for a in articles:
                exists = (
                    db.query(UserNotificationStatus)
                    .filter(
                        UserNotificationStatus.user_id == r.user_id,
                        UserNotificationStatus.article_id == a.id,
                        UserNotificationStatus.channel == "email",
                    )
                    .first()
                )
                if not exists:
                    db.add(
                        UserNotificationStatus(user_id=r.user_id, article_id=a.id, channel="email")
                    )
    if not dry_run:
        db.commit()

    logger.info(
        "Veille email: %d recipients, %d sent, %d failed (dry_run=%s)",
        len(recipients), len(sent), len(failed), dry_run,
    )
    return {
        "status": "dry_run" if dry_run else "sent",
        "articles": len(articles),
        "recipients": len(recipients),
        "by_language": by_language,
        "sent": sent,
        "failed": failed,
    }
